version: "3"

services:
  php:
    # image: lu7766lu7766/jac-php-mssql-apache:latest
    # image: namoshek/php-mssql:7.4-fpm
    image: namoshek/php-mssql:8.4-fpm-alpine-swoole
    container_name: php-fpm
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    # ports:
    #   - "9000:9000" # PHP-FPM 預設端口
    environment:
      - PHP_ENV=development # 可根據需要調整環境變數

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80" # HTTP 端口
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx:/etc/nginx/conf.d # 自定義 Nginx 配置
    depends_on:
      - php
